### ISSUE TITLE
[Bug]: AttributeError: 'duckdb.DuckDBPyConnection' object has no attribute 'autocommit' 

### ISSUE THREAD

**Issue by Mageswaran1989** [Mause/duckdb_engine#366]
### What happened?

With the latest version of Sqlalchemy, duckdb and [duckdb-engine](https://github.com/Mause/duckdb_engine/), following error is thrown while trying for ping test.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in ping
  File "/Users/mageswarandhandapani/miniforge3/envs/duckdb/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 867, in do_ping
    before_autocommit = dbapi_connection.autocommit
  File "/Users/mageswarandhandapani/miniforge3/envs/duckdb/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1086, in __getattr__
    return getattr(self.dbapi_connection, key)
  File "/Users/mageswarandhandapani/miniforge3/envs/duckdb/lib/python3.8/site-packages/duckdb_engine/__init__.py", line 66, in __getattr__
    return getattr(self.c, name)
AttributeError: 'duckdb.DuckDBPyConnection' object has no attribute 'autocommit'
```

Verion Details:

- duckdb-0.4.0
- duckdb-engine-0.3.3
- sqlalchemy-1.4.40

### To Reproduce

Pip:

```bash
conda create --name duckdb python=3.8
spurce activate duckdb
pip install duckdb-engine==0.3.3
...
Successfully installed duckdb-0.4.0 duckdb-engine-0.3.3 numpy-1.23.1 sqlalchemy-1.4.40
```

Python code:

```python
from contextlib import closing
from sqlalchemy.engine import Engine
import sqlalchemy as sa

def get_engine():
    return sa.create_engine("duckdb:///:memory:")

def ping(engine: Engine) -> bool:
    with closing(engine.raw_connection()) as conn:
        return engine.dialect.do_ping(conn)

ping(get_engine())
```

### DuckDB Engine Version

0.3.3

### DuckDB Version

0.4.0

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in ping
  File "/Users/mageswarandhandapani/miniforge3/envs/duckdb/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 867, in do_ping
    before_autocommit = dbapi_connection.autocommit
  File "/Users/mageswarandhandapani/miniforge3/envs/duckdb/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1086, in __getattr__
    return getattr(self.dbapi_connection, key)
  File "/Users/mageswarandhandapani/miniforge3/envs/duckdb/lib/python3.8/site-packages/duckdb_engine/__init__.py", line 66, in __getattr__
    return getattr(self.c, name)
AttributeError: 'duckdb.DuckDBPyConnection' object has no attribute 'autocommit'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
@Mageswaran1989 are you able to confirm is duckdb-engine 0.4.0 fixes this issue?

**Comment by Mageswaran1989** [comment]
Its working! Thanks
