### ISSUE TITLE
[Bug]: Introspection for type VARCHAR[] fails

### ISSUE THREAD

**Issue by EmilRex** [Mause/duckdb_engine#369]
### What happened?

The dialect doesn't appear to accept DuckDB's `VARCHAR[]` type and instead raises `TypeError: expected string or bytes-like object`.

### To reproduce
```py
import sqlalchemy

e = sqlalchemy.create_engine('duckdb:///test.duckdb')
e.execute("create table test as (select ['a', 'b', 'c'] as col);")

sqlalchemy.inspect(e).get_columns('test')
```

### DuckDB Engine Version

0.3.4

### DuckDB Version

0.4.0

### SQLAlchemy Version

1.4.39

### Relevant log output

```shell
Python 3.9.12 (main, Mar 26 2022, 15:44:31) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy
>>> e = sqlalchemy.create_engine('duckdb:///test.duckdb')
>>> e.execute("create table test as (select ['a', 'b', 'c'] as col);")
<sqlalchemy.engine.cursor.LegacyCursorResult object at 0x1042c8b80>
>>> sqlalchemy.inspect(e).get_columns('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/emilchristensen/.virtualenvs/orbit/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File "/Users/emilchristensen/.virtualenvs/orbit/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/emilchristensen/.virtualenvs/orbit/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3850, in get_columns
    column_info = self._get_column_info(
  File "/Users/emilchristensen/.virtualenvs/orbit/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3887, in _get_column_info
    attype = re.sub(r"\(.*\)", "", format_type)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
Hi @EmilRex, thanks for raising this! It looks like this has been fixed in the latest `duckdb` prerelease build, are you able to test with that and confirm it behaves as you expect?

**Comment by EmilRex** [comment]
HI @Mause 👋 Thank you for responding and for the pointer! I'll go test with the prerelease, see if that fixes it, and report back.

**Comment by EmilRex** [comment]
Can confirm that with `duckdb==0.4.1.dev1580`, an error is no longer raised. The new behavior is,

```py
>>> import sqlalchemy

>>> e = sqlalchemy.create_engine('duckdb:///test.duckdb')

>>> e.execute("create table test as (select ['a', 'b', 'c'] as col);")
<sqlalchemy.engine.cursor.LegacyCursorResult object at 0x105b80df0>

>>> sqlalchemy.inspect(e).get_columns('test')
<stdin>:1: SAWarning: Did not recognize type 'list' of column 'col'
[{'name': 'col', 'type': NullType(), 'nullable': True, 'default': None, 'autoincrement': False, 'comment': None}]
```
