### ISSUE TITLE
[Bug]: `sqlalchemy.exc.NoSuchTableError` when trying to obtain table metadata from parquet

### ISSUE THREAD

**Issue by multimeric** [Mause/duckdb_engine#550]
### What happened?

Using `Table("foo.parquet", md, autoload_with=eng)` fails, since SQLAlchemy doesn't believe this parquet file is a table. However, DuckDB itself has no issue querying the file as if it existed.

More details below in the Python session output.

### DuckDB Engine Version

duckdb-engine==0.6.8

### DuckDB Version

duckdb==0.6.1

### Relevant log output

```shell
>>> from sqlalchemy import create_engine, MetaData, Table
>>> eng = create_engine("duckdb:///:memory:")
>>> md = MetaData()
>>> # Trying to autoload metadata fails
>>> Table("metadata.parquet", md, autoload_with=eng)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in __new__
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 774, in reflect_table
    for col_d in self.get_columns(
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3859, in get_columns
    table_oid = self.get_table_oid(
  File "<string>", line 2, in get_table_oid
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/milton.m/Programming/CuratedAtlasQueryPy/venv/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3739, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: metadata.parquet  
>>> # It succeeds if we don't try to autoload
>>> Table("metadata.parquet", md)
Table('metadata.parquet', MetaData(), schema=None)
>>> # Also, we can query the parquet file with no issues
>>> cur = eng.execute("SELECT * FROM 'metadata.parquet' LIMIT 4;")
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
Hi, thanks for raising an issue!

This isn't actually a bug, I'd say this is expected. When you do a `SELECT * FROM 'whatever.parquet'` query, under the hood, DuckDB searches for a table with a matching name, and when it doesn't find one, rewrites it using a "replacement scan", into `SELECT * FROM read_parquet('whatever.parquet')`, where `read_parquet` is a "table function" (that is, a function that returns a table).

Obviously it doesn't do this replacement scan lookup when you try to query the system metadata tables for tables, which is what happens when you do reflection, but if you don't use reflection, and just use it as a table in a query, the replacement scan runs and it succeeds.

Hope this helps!

**Comment by multimeric** [comment]
Understandable, since it's not a real table. But is there a reasonable way to *get* the metadata for SQLAlchemy, if not through normal reflection?

**Comment by Mause** [comment]
You can create it as a real table? The following would work:

```sql
CREATE TEMP TABLE whatever AS FROM 'whatever.parquet';
```
Or the same using a view instead if you don't want to actually load the data. You should then be able to use the standard reflection machinery

Note that the TEMP table will only persist for that session/connection
