### ISSUE TITLE
[Bug]: Setting config on connect fails for non-global config options

### ISSUE THREAD

**Issue by teague-23andme** [Mause/duckdb_engine#758]
### What happened?

Trying to set config options that are non-global at connect time (through `connect_args['config']`) fails.

This seems to be an issue within DuckDB itself, but it would be great to have a mechanism for passing in things like `file_search_path` as part of the connection (or even as part of the connection string).

### DuckDB Engine Version

0.9.2

### DuckDB Version

0.8.1

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/user/.local/lib/python3.10/site-packages/duckdb_engine/__init__.py", line 206, in connect
    conn = duckdb.connect(*cargs, **cparams)
duckdb.InternalException: INTERNAL Error: Could not set option "file_search_path" as a global option

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/git/target_triage/etl/checks.py", line 16, in <module>
    cursor = conn.execute_query(text('SELECT * FROM tht LIMIT 10;'))
  File "/home/user/.local/lib/python3.10/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 1430, in execute_query
    with self.get_connection() as connection:
  File "/opt/Python-3.10.5/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/user/.local/lib/python3.10/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 1414, in get_connection
    with self.engine.connect() as connection:
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/user/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/user/.local/lib/python3.10/site-packages/duckdb_engine/__init__.py", line 206, in connect
    conn = duckdb.connect(*cargs, **cparams)
sqlalchemy.exc.InternalError: (duckdb.InternalException) INTERNAL Error: Could not set option "file_search_path" as a global option
(Background on this error at: https://sqlalche.me/e/20/2j85)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
The InternalException has been fixed upstream, and realistically, this is an upstream issue as well - there's no way for me to fix this in duckdb_engine at the present, as there's presently no way to determine programmatically which settings can be set globally.
