### ISSUE TITLE
[Bug]: Registering a pandas df does no longer work with sqlalchemy >=2

### ISSUE THREAD

**Issue by jlootensdataroots** [Mause/duckdb_engine#794]
### What happened?

Can't register dataframes for as specified in https://github.com/Mause/duckdb_engine#how-to-register-a-pandas-dataframe with sqlalchemy>=2.
```
with engine.connect() as conn:
    conn.execute("register", ("df", df)) <--- stack trace in relevant log output
    conn.execute(f"INSERT INTO {table_name} SELECT * FROM df")
```

Works when downgrading to sqlalchemy==1.4

(Might just need a doc update?)

### DuckDB Engine Version

0.9.0

### DuckDB Version

0.9.2

### SQLAlchemy Version

2.0.21

### Relevant log output

```shell
/Users/***/Documents/projects/project/.venv/lib/python3.10/site-packages/duckdb_engine/__init__.py:162: DuckDBEngineWarning: duckdb-engine doesn't yet support reflection on indices
  warnings.warn(
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/***/.vscode/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/***/.vscode/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/***/.vscode/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/***/.vscode/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/***/.vscode/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/***/.vscode/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/***/Documents/projects/project/scripts/duckdbify.py", line 170, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/***/Documents/projects/project/scripts/duckdbify.py", line 166, in main
    export_to_duck(df_tables, junction_tables, engine)
  File "/Users/***/Documents/projects/project/scripts/duckdbify.py", line 102, in export_to_duck
    create_table(table_name, df, constraints=[PrimaryKeyConstraint('id')], engine=engine)
  File "/Users/***/Documents/projects/project/scripts/duckdbify.py", line 89, in create_table
    conn.execute("register", ("df", df))
  File "/Users/***/Documents/projects/project/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1406, in execute
    distilled_parameters = _distill_params_20(parameters)
  File "lib/sqlalchemy/cyextension/util.pyx", line 26, in sqlalchemy.cyextension.util._distill_params_20
  File "lib/sqlalchemy/cyextension/util.pyx", line 17, in sqlalchemy.cyextension.util._check_item
sqlalchemy.exc.ArgumentError: List argument must consist only of tuples or dictionaries
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mause** [comment]
Hey there! Yes this is a docs issue, in sqlalchemy 2 you have to use the `exec_driver_sql` instead, see here: https://github.com/Mause/duckdb_engine/blob/f92dc4dcd2869d6161d778c672ebf8750f2455f7/duckdb_engine/tests/test_integration.py#L12
