### ISSUE TITLE
[Bug]: `Sequence` doesn't work with ORM

### ISSUE THREAD

**Issue by dhirschfeld** [Mause/duckdb_engine#828]
### What happened?

Am I doing something wrong, or should the below work?

```python

import sqlalchemy as sa
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
)


class Base(DeclarativeBase):
    pass



pkid = sa.Sequence('test_table_pkid')


class TestTable(Base):
    __tablename__ = "TestTable"

    pkid: Mapped[int] = mapped_column(
        autoincrement=pkid,
        server_default=pkid.next_value(),
        primary_key=True,
    )
    value: Mapped[float]



engine = sa.create_engine("duckdb:///:memory:", echo=True)
Base.metadata.create_all(engine)
```

### DuckDB Engine Version

0.9.2

### DuckDB Version

0.9.1

### SQLAlchemy Version

2.0.22

### Relevant log output

```shell
2023-11-14 23:26:54,424 INFO sqlalchemy.engine.Engine select current_schema()
2023-11-14 23:26:54,424 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-14 23:26:54,440 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-14 23:26:54,440 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = ? AND pg_catalog.pg_class.relkind = ANY (ARRAY[?, ?, ?, ?, ?]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != ?
2023-11-14 23:26:54,440 INFO sqlalchemy.engine.Engine [dialect duckdb+duckdb_engine does not support caching 0.00100s] ('TestTable', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2023-11-14 23:26:59,370 INFO sqlalchemy.engine.Engine
CREATE TABLE "TestTable" (
        pkid INTEGER DEFAULT nextval('test_table_pkid') NOT NULL,
        value FLOAT NOT NULL,
        PRIMARY KEY (pkid)
)


2023-11-14 23:26:59,371 INFO sqlalchemy.engine.Engine [no key 0.00083s] ()
2023-11-14 23:26:59,373 INFO sqlalchemy.engine.Engine ROLLBACK
---------------------------------------------------------------------------
CatalogException                          Traceback (most recent call last)
File C:\python\envs\dev-py310\lib\site-packages\sqlalchemy\engine\base.py:1969, in Connection._exec_single_context(self, dialect, context, statement, parameters)
   1968     if not evt_handled:
-> 1969         self.dialect.do_execute(
   1970             cursor, str_statement, effective_parameters, context
   1971         )
   1973 if self._has_events or self.engine._has_events:

File C:\python\envs\dev-py310\lib\site-packages\sqlalchemy\engine\default.py:922, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    921 def do_execute(self, cursor, statement, parameters, context=None):
--> 922     cursor.execute(statement, parameters)

File C:\python\envs\dev-py310\lib\site-packages\duckdb_engine\__init__.py:144, in ConnectionWrapper.execute(self, statement, parameters, context)
    143     else:
--> 144         self.__c.execute(statement, parameters)
    145 except RuntimeError as e:

CatalogException: Catalog Error: Sequence with name test_table_pkid does not exist!

The above exception was the direct cause of the following exception:

ProgrammingError                          Traceback (most recent call last)

...<SNIP>...

ProgrammingError: (duckdb.duckdb.CatalogException) Catalog Error: Sequence with name test_table_pkid does not exist!
[SQL:
CREATE TABLE "TestTable" (
        pkid INTEGER DEFAULT nextval('test_table_pkid') NOT NULL,
        value FLOAT NOT NULL,
        PRIMARY KEY (pkid)
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhirschfeld** [comment]
As a data-point, it seems to work fine with `sa.Column` rather than `mapped_column`:
```python
In [1]: import sqlalchemy as sa
   ...: from sqlalchemy.orm import (
   ...:     DeclarativeBase,
   ...:     Mapped,
   ...:     mapped_column,
   ...: )
   ...:
   ...:
   ...: class Base(DeclarativeBase):
   ...:     pass
   ...:
   ...:
   ...:
   ...: pkid = sa.Sequence('test_table_pkid')
   ...:
   ...:
   ...: class TestTable(Base):
   ...:     __tablename__ = "TestTable"
   ...:
   ...:     pkid = sa.Column(sa.Integer, pkid, server_default=pkid.next_value(), primary_key=True)
   ...:     value: Mapped[float]
   ...:

In [2]: engine = sa.create_engine("duckdb:///:memory:", echo=True)
   ...: Base.metadata.create_all(engine)
2023-11-14 23:34:56,410 INFO sqlalchemy.engine.Engine select current_schema()
2023-11-14 23:34:56,410 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-11-14 23:34:56,410 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-11-14 23:34:56,410 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = ? AND pg_catalog.pg_class.relkind = ANY (ARRAY[?, ?, ?, ?, ?]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != ?
2023-11-14 23:34:56,410 INFO sqlalchemy.engine.Engine [dialect duckdb+duckdb_engine does not support caching 0.00082s] ('TestTable', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2023-11-14 23:34:57,658 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ? AND pg_catalog.pg_class.relname = ? AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != ?
2023-11-14 23:34:57,658 INFO sqlalchemy.engine.Engine [dialect duckdb+duckdb_engine does not support caching 0.00149s] ('S', 'test_table_pkid', 'pg_catalog')
2023-11-14 23:34:57,677 INFO sqlalchemy.engine.Engine CREATE SEQUENCE test_table_pkid
2023-11-14 23:34:57,677 INFO sqlalchemy.engine.Engine [no key 0.00041s] ()
2023-11-14 23:34:57,680 INFO sqlalchemy.engine.Engine
CREATE TABLE "TestTable" (
        pkid INTEGER DEFAULT nextval('test_table_pkid') NOT NULL,
        value FLOAT NOT NULL,
        PRIMARY KEY (pkid)
)


2023-11-14 23:34:57,681 INFO sqlalchemy.engine.Engine [no key 0.00063s] ()
2023-11-14 23:34:57,689 INFO sqlalchemy.engine.Engine COMMIT
```

**Comment by dhirschfeld** [comment]
It also works if you explicitly pass the metadata:
```
pkid = sa.Sequence('test_table_pkid', metadata=Base.metadata)
```

**Comment by dhirschfeld** [comment]
I guess it's probably an upstream issue?

**Comment by Mause** [comment]
Uh, no, the issue is this line:

```py
        autoincrement=pkid,
```

the sequence shouldn't be passed as the autoincrement value? It works fine if you pass it as a positional parameter, as it was in the Column example

**Comment by dhirschfeld** [comment]
Ah true! 🤦 

I was sure I tried that when translating to the `mapped_column` format but I think I must've had several bugs at once.

Can confirm it works fine if you pass the sequence as a positional argument!

**Comment by JoaoGMSF** [comment]
I believe I am encountering a similar issue. I am trying to apply a migration with Alembic from the following model:
```
from sqlalchemy import Column, Integer, Sequence
from sqlalchemy.orm import DeclarativeBase

class Base(DeclarativeBase):
    pass

class SegmentationTest(Base):
    __tablename__ = 'segmentation_test'

    seq_id = Sequence('seq_id', metadata=Base.metadata)
    id = Column(Integer, seq_id, server_default=seq_id.next_value(), primary_key=True)
    value = Column(Integer)
```
However, I am getting the following error log:
```
INFO  [alembic.runtime.migration] Context impl AlembicDuckDBImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 12f702794dab -> 537e49e58c51, secundary
Traceback (most recent call last):
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/duckdb_engine/__init__.py", line 139, in execute
    self.__c.execute(statement, parameters)
duckdb.duckdb.CatalogException: Catalog Error: Sequence with name seq_id does not exist!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jonga/.pyenv/versions/alembic-duckdb/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/config.py", line 641, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/config.py", line 631, in main
    self.run_cmd(cfg, options)
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/config.py", line 608, in run_cmd
    fn(
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jonga/Documents/tests/alembic+DuckDB/migrations/env.py", line 85, in <module>
    run_migrations_online()
  File "/home/jonga/Documents/tests/alembic+DuckDB/migrations/env.py", line 79, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "/home/jonga/Documents/tests/alembic+DuckDB/migrations/versions/537e49e58c51_secundary.py", line 23, in upgrade
    op.create_table('segmentation_test',
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/operations/ops.py", line 1311, in create_table
    return operations.invoke(op)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/operations/base.py", line 445, in invoke
    return fn(self, operation)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/operations/toimpl.py", line 131, in create_table
    operations.impl.create_table(table)
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/ddl/impl.py", line 366, in create_table
    self._exec(schema.CreateTable(table))
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/alembic/ddl/impl.py", line 207, in _exec
    return conn.execute(construct, multiparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1529, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/jonga/.pyenv/versions/3.11.9/envs/alembic-duckdb/lib/python3.11/site-packages/duckdb_engine/__init__.py", line 139, in execute
    self.__c.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (duckdb.duckdb.CatalogException) Catalog Error: Sequence with name seq_id does not exist!
[SQL: 
CREATE TABLE segmentation_test (
        id INTEGER DEFAULT nextval('seq_id') NOT NULL, 
        value INTEGER, 
        PRIMARY KEY (id)
)

]
```
Is there something wrong with my code? I replicated it as I saw in the [documentation](https://docs.sqlalchemy.org/en/14/core/defaults.html#associating-a-sequence-as-the-server-side-default).

Also, I am using these package versions:
```
alembic           1.13.1
duckdb            1.0.0
duckdb_engine     0.13.0
SQLAlchemy        2.0.31
```
