### ISSUE TITLE
Investigate possible chunking issue

### ISSUE THREAD

**Issue by Mause** [Mause/duckdb_engine#92]
See https://github.com/bmeares/Meerschaum/blob/cff0c913e31d5bf95d311fe05077493267d036a5/meerschaum/connectors/sql/_sql.py#L98

**Comment by Mause** [comment]
@bmeares do you have any detaills?

**Comment by bmeares** [comment]
@Mause Sorry for the late reply, I just saw this. I'm on the road last week and next but will dive in soon when I can. Thanks for tagging the line in Meerschaum for context in case other developers want to investigate.

When I get back on my laptop, I'll post the stacktrace and give updates on what I find.

**Comment by bmeares** [comment]
I threw together some pytest test in `test_pandas.py` which is in #97 .

`pd.read_sql()` with a `chunksize` other than `None` invokes [`sqlalchemy.engine.cursor.CursorResult._fetchmany_impl()`](https://github.com/sqlalchemy/sqlalchemy/blob/2f100a7d4bb143e1f8674a388d8d305be3051bd6/lib/sqlalchemy/engine/cursor.py#L1795) which calls [`sqlalchemy.engine.cursor.CursorFetchStrategy,fetchmany()`](https://github.com/sqlalchemy/sqlalchemy/blob/2f100a7d4bb143e1f8674a388d8d305be3051bd6/lib/sqlalchemy/engine/cursor.py#L958). The `CursorResult.cursor` object is `None` which breaks `fetchmany()`.

Here is the raw traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bmeares/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 1244, in _query_iterator
    data = result.fetchmany(chunksize)
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1022, in fetchmany
    return self._manyrow_getter(self, size)
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 541, in manyrows
    rows = self._fetchmany_impl(num)
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 1796, in _fetchmany_impl
    return self.cursor_strategy.fetchmany(self, self.cursor, size)
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 969, in fetchmany
    self.handle_exception(result, dbapi_cursor, e)
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 937, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1998, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 963, in fetchmany
    l = dbapi_cursor.fetchmany(size)
TypeError: 'NoneType' object is not callable
```

and here is the output from `pytest`:

```
=============================== FAILURES ===============================
______________________ test_read_sql[chunksize0] _______________________

chunksize = (None,)

    @pytest.mark.parametrize(params_strings['read_sql'], params['read_sql'])
    def test_read_sql(
        chunksize: Optional[int],
    ):
        eng = create_engine("duckdb:///:memory:")
        sample_df.to_sql(name='test_read', con=eng, if_exists='replace')
        query = "SELECT * FROM test_read"
        result = pd.read_sql(
            query,
            eng,
            chunksize=chunksize,
        )
>       chunks = [result] if chunksize is None else [chunk for chunk in result]

duckdb_engine/tests/test_pandas.py:83:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
duckdb_engine/tests/test_pandas.py:83: in <listcomp>
    chunks = [result] if chunksize is None else [chunk for chunk in result]
../.local/lib/python3.9/site-packages/pandas/io/sql.py:1244: in _query_iterator
    data = result.fetchmany(chunksize)
../.local/lib/python3.9/site-packages/sqlalchemy/engine/result.py:1022: in fetchmany
    return self._manyrow_getter(self, size)
../.local/lib/python3.9/site-packages/sqlalchemy/engine/result.py:541: in manyrows
    rows = self._fetchmany_impl(num)
../.local/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py:1796: in _fetchmany_impl
    return self.cursor_strategy.fetchmany(self, self.cursor, size)
../.local/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py:969: in fetchmany
    self.handle_exception(result, dbapi_cursor, e)
../.local/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py:937: in handle_exception
    result.connection._handle_dbapi_exception(
../.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1998: in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
../.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py:207: in raise_
    raise exception
```

I don't understand why it breaks with a `chunksize` of `None` in `pytest`, but it works for me in the REPL. I also ran into issues when calling `df.to_sql()` with `if_exists=True`, but that's another issue we can look into another time.

I need to spend more time digging into the `duckdb_engine` source, but I thought this might be helpful for now. I'll post more updates when I can!

**Comment by Mause** [comment]
@bmeares this is hopefully fixed now - please let me know if you find any further issues 💜

**Comment by bmeares** [comment]
Thank you for working on the chunking! I was doing some tests and was able to pull some chunks, but the chunks were the wrong size (1024 instead of the specified `chunksize` of 100).
I tried to reproduce the problem, but `psycopg2` is getting in the way and breaking with a `KeyError`. Below is the stack trace:

```python
Python 3.9.5 (default, May 14 2021, 00:00:00)
[GCC 11.1.1 20210428 (Red Hat 11.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import sqlalchemy
>>> df = pd.DataFrame({'foo': [0,1,2,3,4,5,6,7,8,9]})
>>> engine = sqlalchemy.create_engine("duckdb:///:memory:")
>>> df.to_sql('test', engine)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bmeares/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 2779, in to_sql
    sql.to_sql(
  File "/home/bmeares/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 601, in to_sql
    pandas_sql.to_sql(
  File "/home/bmeares/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 1411, in to_sql
    table.insert(chunksize, method=method)
  File "/home/bmeares/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 845, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/home/bmeares/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 762, in _execute_insert
    conn.execute(self.table.insert(), data)
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1262, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1998, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1750, in _execute_context
    self.dialect.do_executemany(
  File "/home/bmeares/.local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 943, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/bmeares/.local/lib/python3.9/site-packages/psycopg2/extras.py", line 1280, in execute_values
    sql = sql.encode(_ext.encodings[cur.connection.encoding])
KeyError: None
>>> 
```
I've tweaked `test_pandas.py` in #105 to address some of the issues I ran into.

Thank you again so much for working on this. I hope I'm helping by testing, and I know `duckdb_engine` is still a very basic `sqlalchemy` wrapper so bugs are expected. Your work is greatly appreciated!
